module.exports = {
    URBANE: {
        TOPIC_URL: ''
    },
    ZIMO: {
        TOPIC_URL: 'data/Fly/scootor/'
    },
    FITRIDER: {
        TOPIC_URL: 'bike'
    },
    TELTONIKA: {
        AVLIDS: {
            0: 'noEvent',
            239: 'ignition',
            240: 'movement',
            80: 'dataMode',
            21: 'networkSignal', // gsmSignal
            200: 'sleepMode',
            69: 'gnssStatus',
            181: 'gnssPDOP',
            182: 'gnssHDOP',
            66: 'externalVoltage',
            24: 'speed',
            205: 'gsmCellId',
            206: 'gsmAreaCode',
            67: 'batteryVoltage',
            68: 'batteryCurrent',
            241: 'activeGsmOperator',
            199: 'tripOdometer',
            16: 'totalOdometer',
            1: 'digitalInput1',
            9: 'analogInput1',
            179: 'digitalOutput1',
            12: 'fuelUsedGPS',
            13: 'fuelRateGPS',
            17: 'axisX',
            18: 'axisY',
            19: 'axisZ',
            11: 'iccid', // iccid1
            14: 'iccid2',
            10: 'sdStatus',
            2: 'digitalInput2',
            3: 'digitalInput3',
            262: 'digitalInput4',
            6: 'analogInput2',
            180: 'digitalOutput2',
            72: 'dallasTemp1',
            73: 'dallasTemp2',
            74: 'dallasTemp3',
            75: 'dallasTemp4',
            76: 'dallasTempID1',
            77: 'dallasTempID2',
            79: 'dallasTempID3',
            71: 'dallasTempID4',
            78: 'iButton',
            207: 'rfid',
            15: 'ecoScore',
            113: 'batteryLevel',
            116: 'chargeStatus',
            238: 'mac', // UserId
            25: 'bleTemp1',
            26: 'bleTemp2',
            27: 'bleTemp3',
            28: 'bleTemp4',
            29: 'ble1BatteryVoltage',
            20: 'ble2BatteryVoltage',
            22: 'ble3BatteryVoltage',
            23: 'ble4BatteryVoltage',
            86: 'ble1Humidity',
            104: 'ble2Humidity',
            106: 'ble3Humidity',
            108: 'ble4Humidity',
            263: 'btStatus',
            303: 'instantMovement',
            381: 'gndSense',
            387: 'iso6709Coordinates',
            800: 'extendedEternalVoltage',
            839: 'extendedAnalogInput1',
            840: 'extendedAnalogInput2',
            841: 'doutOvercurrent1',
            842: 'doutOvercurrent2',
            155: 'geoFenceZone1',
            156: 'geoFenceZone2',
            157: 'geoFenceZone3',
            158: 'geoFenceZone4',
            159: 'geoFenceZone5',
            61: 'geoFenceZone6',
            62: 'geoFenceZone7',
            63: 'geoFenceZone8',
            64: 'geoFenceZone9',
            65: 'geoFenceZone10',
            70: 'geoFenceZone11',
            88: 'geoFenceZone12',
            91: 'geoFenceZone13',
            92: 'geoFenceZone14',
            93: 'geoFenceZone15',
            94: 'geoFenceZone16',
            95: 'geoFenceZone17',
            96: 'geoFenceZone18',
            97: 'geoFenceZone19',
            98: 'geoFenceZone20',
            99: 'geoFenceZone21',
            153: 'geoFenceZone22',
            154: 'geoFenceZone23',
            190: 'geoFenceZone24',
            191: 'geoFenceZone25',
            192: 'geoFenceZone26',
            193: 'geoFenceZone27',
            194: 'geoFenceZone28',
            195: 'geoFenceZone29',
            196: 'geoFenceZone30',
            197: 'geoFenceZone31',
            198: 'geoFenceZone32',
            208: 'geoFenceZone33',
            209: 'geoFenceZone34',
            216: 'geoFenceZone35',
            217: 'geoFenceZone36',
            218: 'geoFenceZone37',
            219: 'geoFenceZone38',
            220: 'geoFenceZone39',
            221: 'geoFenceZone40',
            222: 'geoFenceZone41',
            223: 'geoFenceZone42',
            224: 'geoFenceZone43',
            225: 'geoFenceZone44',
            226: 'geoFenceZone45',
            227: 'geoFenceZone46',
            228: 'geoFenceZone47',
            229: 'geoFenceZone48',
            230: 'geoFenceZone49',
            231: 'geoFenceZone50',
            175: 'autoGeofence',
            250: 'trip',
            255: 'overSpeedingEvent',
            257: 'crashTraceData',
            318: 'gnssJamming',
            251: 'idling',
            252: 'unplug',
            253: 'greenDrivingType',
            246: 'towing',
            247: 'crashDetection',
            248: 'immobilizer',
            254: 'greenDrivingValue',
            249: 'jamming',
            243: 'greenDrivingEventDuration',
            236: 'alarm',
            242: 'manDown',
            310: 'movementEvent',
            389: 'buttonClick',
            339: 'serialNo',
            340: 'masterControlFmVersion',
            341: 'eScooterError',
            342: 'alarmCode',
            344: 'lockStatus',
            345: 'buzzerAlarmStatus',
            346: 'externalBatteryStatus',
            347: 'chargeStatusScooter',
            349: 'currentOperationMode',
            350: 'internalBatteryStatus',
            351: 'externalBatteryVoltage',
            352: 'batteryPer',
            353: 'actualRemainingMileage',
            354: 'predictedRemainingMileage',
            355: 'speed',  // ScooterSpeed
            356: 'totalMileage',
            357: 'singleMileage',
            358: 'totalOperationTime',
            359: 'totalRidingTime',
            360: 'singleOperationTime',
            361: 'singleRidingTime',
            362: 'bodyTemperature',
            363: 'internalBatteryTemperature1',
            364: 'internalBatteryTemperature2',
            365: 'externalBatteryTemperature1',
            366: 'supplyVoltage',
            367: 'externalBatteryTemperature2',
            369: 'averageSpeed',
            370: 'externalBatteryFmVersion1',
            371: 'internalBatteryFmVersion1',
            372: 'instrumentPanelFmVersion1',
            374: 'internalBatteryCapacity',
            375: 'externalBatteryCapacity',
            242: 'fallDown',
            800: 'externalVoltage',
            801: 'parkBrake',
            802: 'selected',
            803: 'selectedChargeMode',
            804: 'chargerVoltage',
            805: 'chargerCurrent',
            806: 'chargeControlMode',
            807: 'chargeBMSCOMTimeout',
            808: 'chargerCRCViolation',
            809: 'chargerMCViolation',
            810: 'chargeStatus',
            811: 'chargerVoltageActual',
            812: 'chargerInternalFault',
            813: 'chargerEnergy',
            814: 'chargerCurrentActual',
            815: 'throttlePosition',
            816: 'brakePressed',
            817: 'chargePlug',
            818: 'killSwitchActive',
            819: 'kickStandRelease',
            820: 'powerStrainState',
            821: 'malFunctionIndicator',
            822: 'currentRange',
            823: 'SoHBattery',
            824: 'SoCBattery',
            825: 'vehicleAvailable',
            826: 'chargingActive',
            827: 'remainingChargeTime',
            828: 'remainingCapacity',
            829: 'fullChargeCapacity',
            830: 'drivingDirection',
            831: 'driveMode',
            832: 'parkBrakeActive',
            833: 'totalDistance',
            834: 'tripDistance',
            835: 'vehicleSpeed',
            836: 'ignitionSwitch',
            837: 'ignitionSwitchFast',
            838: 'powerConsumptionCycle'
        },
        COMMANDS: {
            TELTONIKA_TFT100: {
                lock: 'setdigout 0',
                unlock: 'setdigout 1',
                lightOn: '',
                lightOff: '',
                alarmOn: '',
                alarmOff: '',
                track: '',
                getLocation: '',
                setMaxSpeed: '',
                setPingInterval: '',
                setRidePingInterval: '',
                bootOpen: 'setdigout ?1',
                bootClose: 'setdigout ?0'
            },
            TELTONIKA_FMB920: {
                lock: 'setdigout 0',
                unlock: 'setdigout 1',
                lightOn: '',
                lightOff: '',
                alarmOn: '',
                alarmOff: '',
                track: '',
                getLocation: '',
                setMaxSpeed: '',
                setPingInterval: '',
                setRidePingInterval: '',
                bootOpen: 'setdigout ?1',
                bootClose: 'setdigout ?0'
            },
            TELTONIKA_TST100: {
                lock: 'sclockctrl 1',
                unlock: 'sclockctrl 0',
                lightOn: 'scsetconfig 0 32769',
                lightOff: 'scsetconfig 0 32768',
                alarmOn: 'scbuzzerctrl 1 10',
                alarmOff: 'scbuzzerctrl 0 10',
                track: '',
                getLocation: '',
                setMaxSpeed: 'scsetspdlim',
                setPingInterval: '',
                setRidePingInterval: '',
                bootOpen: '',
                bootClose: ''
            },
            TELTONIKA_TST100_1: {
                lock: 'scenginectrl 0',
                unlock: 'scenginectrl 1',
                lightOn: 'scsetledswitch 1',
                lightOff: 'scsetledswitch 0',
                alarmOn: 'scbuzzerctrl 1 10',
                alarmOff: 'scbuzzerctrl 0 10',
                track: '',
                getLocation: '',
                setMaxSpeed: 'scsetspdlim',
                setPingInterval: '',
                setRidePingInterval: '',
                bootOpen: '',
                bootClose: ''
            }
        }
    },
    BL10: {
        VOLTAGE_LEVEL: [
            { volt: 4.16, percentage: 100 },
            { volt: 4.11, percentage: 95 },
            { volt: 4.08, percentage: 90 },
            { volt: 4.04, percentage: 85 },
            { volt: 4.01, percentage: 80 },
            { volt: 3.98, percentage: 75 },
            { volt: 3.95, percentage: 70 },
            { volt: 3.92, percentage: 65 },
            { volt: 3.88, percentage: 60 },
            { volt: 3.85, percentage: 55 },
            { volt: 3.82, percentage: 50 },
            { volt: 3.79, percentage: 45 },
            { volt: 3.76, percentage: 40 },
            { volt: 3.72, percentage: 35 },
            { volt: 3.69, percentage: 30 },
            { volt: 3.66, percentage: 25 },
            { volt: 3.63, percentage: 20 },
            { volt: 3.60, percentage: 15 },
            { volt: 3.56, percentage: 10 },
            { volt: 3.53, percentage: 05 },
            { volt: 3.50, percentage: 0 }
        ],
        PROTOCOLS: {
            loginInformation: '01',
            heartBeat: '23',
            commandResponse: '21',
            gpsLocationInformation: '32',
            locationInformationAlarm: '33',
            onlineCommand: '80',
            informationTransmissionPacket: '98',
            wifiInformationPacket: '2c'
        },
        INFORMATION_MODULE_NO: {
            '00': 'imei',
            '01': 'imsi',
            '02': 'iccid',
            '03': 'chipId',
            '04': 'bluetoothMac'
        },
        serialNo: {},
        callbackResponse: {
            'success': true
        }
    },
    MQTT_MANUFACTURERS: [
        'ZIMO',
        'FITRIDER_SCOOTER',
        'URBANE_SCOOTER'
    ],
    GOGOBIKE: {
        serialNo: {}
    },
    IOT_LOG_TYPE: {
        COMMAND: 1,
        CALLBACK: 2
    },
    IOT_COMMAND_NAME: {
        LOCK: 'Lock',
        UNLOCK: 'Unlock',
        ALARM_ON: 'AlarmOn',
        ALARM_OFF: 'AlarmOff',
        TRACK: 'Track',
        SET_PING_INTERVAL: 'SetPingInterval',
        SET_RIDE_PING_INTERVAL: 'SetRidePingInterval',
        POSITION_PING_INTERVAL: 'SetPositionPingInterval',
        LOCATION: 'Location',
        LIGHT_ON: 'LightOn',
        LIGHT_OFF: 'LightOff',
        SET_MAX_SPEED: 'SetMaxSpeed',
        BUZZ_ON: 'BuzzOn',
        BOOT_OPEN: 'BootOpen',
        BOOT_CLOSE: 'BootClose',
        UPLOAD_FILE_TO_SCOOTER: 'UploadFilesToScooter',
        PLAY_AUDIO: 'PlayAudio',
        AUTO_PLAY_ENABLE: 'AutoPlayEnable',
        AUTO_PLAY_DISABLE: 'AutoPlayDisable',
        GET_FIRMWARE_INFO: 'GetFirmwareInfo',
        GET_MAC_ADDRESS: 'GetMacAddress',
        GET_SIM_DETAIL: 'GetSimDetail',
    }
};