module.exports = {
    ROLES_PERMISSION: [
        {
            module: 1,
            name: "Dashboard",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 87,
            name: "General Settings",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 88,
            name: "Geo Location",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 21,
            name: "Users",
            keys: ["name", "emails"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 2,
            name: "Riders",
            keys: ["name", "emails"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 22,
            name: "Franchisee",
            keys: ["name", "emails"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 97,
            name: "Dealer",
            keys: ["name", "emails"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 4,
            name: "Vehicle",
            keys: ["type", "registerId", "name"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 10,
            name: "Rides",
            keys: ["rideNumber", "status"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 81,
            name: "Booking Plan",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 83,
            name: "Rental",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 84,
            name: "Rental Payment",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 85,
            name: "Client Payments",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 33,
            name: "Payment",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 6,
            name: "Dispute",
            keys: ["uniqNumber", "rideId.rideNumber"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 8,
            name: "Notifications",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 55,
            name: "FAQs",
            keys: ["question"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 53,
            name: "Static Page",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 58,
            name: "Feedback",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 41,
            name: "Master",
            keys: ["code"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 42,
            name: "Data Bank",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 51,
            name: "Ride Setting",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 52,
            name: "Cancellation Reason",
            keys: ["reason"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 60,
            name: "Action Questionnaire",
            keys: ["question"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 65,
            name: "Zone",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 54,
            name: "Fare Management",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 56,
            name: "Procedure",
            keys: ["name"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 57,
            name: "Promotions",
            keys: ["name", "code"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 67,
            name: "Version",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 9,
            name: "Roles",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 43,
            name: "Location",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 7,
            name: "Service Request",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 91,
            name: "Commission",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 92,
            name: "Commission Payout",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 93,
            name: "Privacy Policy",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 94,
            name: "T&C",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 95,
            name: "Commission Report",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 59,
            name: "Wallet Config",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: true,
                delete: false,
            },
        },
    ],
    ROLES_PERMISSION_FRANCHISEE: [
        {
            module: 1,
            name: "Dashboard",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 87,
            name: "General Settings",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 88,
            name: "Geo Location",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 21,
            name: "Users",
            keys: ["name", "emails"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 2,
            name: "Riders",
            keys: ["name", "emails"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 22,
            name: "Franchisee",
            keys: ["name", "emails"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 97,
            name: "Dealer",
            keys: ["name", "emails"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 4,
            name: "Vehicle",
            keys: ["type", "registerId", "name"],
            permissions: {
                list: true,
                view: true,
                insert: false,
                update: true,
                delete: false,
            },
        },
        {
            module: 10,
            name: "Rides",
            keys: ["rideNumber", "status"],
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 81,
            name: "Booking Plan",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 83,
            name: "Rental",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 84,
            name: "Rental Payment",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 85,
            name: "Client Payments",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 33,
            name: "Payment",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 6,
            name: "Dispute",
            keys: ["uniqNumber", "rideId.rideNumber"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 8,
            name: "Notifications",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 55,
            name: "FAQs",
            keys: ["question"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 53,
            name: "Static Page",
            permissions: {
                list: true,
                view: true,
                insert: false,
                update: true,
                delete: false,
            },
        },
        {
            module: 58,
            name: "Feedback",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 41,
            name: "Master",
            keys: ["code"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 42,
            name: "Data Bank",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 51,
            name: "Ride Setting",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: true,
                delete: false,
            },
        },
        {
            module: 52,
            name: "Cancellation Reason",
            keys: ["reason"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 60,
            name: "Action Questionnaire",
            keys: ["question"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 65,
            name: "Zone",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 54,
            name: "Fare Management",
            permissions: {
                list: true,
                view: false,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 56,
            name: "Procedure",
            keys: ["name"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 57,
            name: "Promotions",
            keys: ["name", "code"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 67,
            name: "Version",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 9,
            name: "Roles",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 43,
            name: "Location",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 7,
            name: "Service Request",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 91,
            name: "Commission",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 92,
            name: "Commission Payout",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 90,
            name: "About Us",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 93,
            name: "Privacy Policy",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 94,
            name: "T&C",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 95,
            name: "Commission Report",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 59,
            name: "Wallet Config",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
    ],
    ROLES_PERMISSION_DEALER: [
        {
            module: 1,
            name: "Dashboard",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 87,
            name: "General Settings",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 88,
            name: "Geo Location",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 21,
            name: "Users",
            keys: ["name", "emails"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 2,
            name: "Riders",
            keys: ["name", "emails"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 22,
            name: "Partner",
            keys: ["name", "emails"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 97,
            name: "Dealer",
            keys: ["name", "emails"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 4,
            name: "Vehicle",
            keys: ["type", "registerId", "name"],
            permissions: {
                list: true,
                view: true,
                insert: false,
                update: true,
                delete: false,
            },
        },
        {
            module: 10,
            name: "Rides",
            keys: ["rideNumber", "status"],
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 81,
            name: "Booking Plan",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 83,
            name: "Rental",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 84,
            name: "Rental Payment",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 85,
            name: "Client Payments",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 33,
            name: "Payment",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 6,
            name: "Dispute",
            keys: ["uniqNumber", "rideId.rideNumber"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 8,
            name: "Notifications",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 55,
            name: "FAQs",
            keys: ["question"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 53,
            name: "Static Page",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 58,
            name: "Feedback",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 41,
            name: "Master",
            keys: ["code"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 42,
            name: "Data Bank",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 51,
            name: "Ride Setting",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 52,
            name: "Cancellation Reason",
            keys: ["reason"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 60,
            name: "Action Questionnaire",
            keys: ["question"],
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 65,
            name: "Zone",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 54,
            name: "Fare Management",
            permissions: {
                list: true,
                view: false,
                insert: true,
                update: true,
                delete: false,
            },
        },
        {
            module: 56,
            name: "Procedure",
            keys: ["name"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 57,
            name: "Promotions",
            keys: ["name", "code"],
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 67,
            name: "Version",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 9,
            name: "Roles",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 43,
            name: "Location",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 7,
            name: "Service Request",
            permissions: {
                list: true,
                view: true,
                insert: true,
                update: true,
                delete: true,
            },
        },
        {
            module: 91,
            name: "Commission",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 92,
            name: "Commission Payout",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 90,
            name: "About Us",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 93,
            name: "Privacy Policy",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 94,
            name: "T&C",
            permissions: {
                list: true,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 95,
            name: "Commission Report",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
        {
            module: 59,
            name: "Wallet Config",
            permissions: {
                list: false,
                view: false,
                insert: false,
                update: false,
                delete: false,
            },
        },
    ],
    PAGE_PERMISSION: {
        DASHBOARD: 1,
        USERS: 21,
        RIDERS: 2,
        FRANCHISEE: 22,
        VEHICLES: 4,
        RIDES: 10,
        PAYMENT: 33,
        DISPUTE: 6,
        NOTIFICATIONS: 8,
        STATIC_PAGE: 53,
        PROMOTIONS: 57,
        // TASK: 58,
        FEEDBACK: 58,
        SERVICE_REQUEST: 7,
        // HEAT_MAP:3,
        // ANALYTICS:5,
        // CONTACT:7,
        ABOUT_US: 90,
        COMMISSION: 91,
        COMMISSION_PAYOUT: 92,
        RENTAL_PAYMENT_CLIENT: 85,
        PRIVACY_POLICY: 93,
        TERMS_AND_CONDITIONS: 94,
        COMMISSION_REPORT: 95,
        MASTER: 41,
        DATABANK: 42,
        LOCATION: 43,
        RIDE_SETTING: 51,
        CANCELLATION_REASON: 52,
        ACTION_QUESTIONNAIRE: 60,
        ZONES: 65,
        NEST: 66,
        FARE_MANAGEMENT: 54,
        PROCEDURE: 56,
        VERSION: 67,
        FAQS: 55,
        WALLET_CONFIG: 59,
        BOOKING_PLAN: 81,
    },
};
