module.exports = {
    BASIC_RADIUS: 0,
    UNLOCK_RADIUS: 0,
    MIN_BATTERY_LEVEL: 0,
    RIDE_RESERVE_TIME_LIMIT: 0,
    RIDE_RESERVE_TIME_FREE_LIMIT: 0,
    PAUSE_TIME_LIMIT: 0,
    SCOOTER_USED_LIMIT: {},
    BOOKING_HABITS_RIDE_LIMIT: {},
    END_WORKING_TIME: '20:00',
    START_WORKING_TIME: '8:00',
    EMAILS_FOR_EXPORT_EXCEL: [],
};
